### PR TITLE
Version 5.0

### PR DESCRIPTION
**Pull request by thedrow**
This PR represents our entire efforts for vine 5.0.
All new features should be merged to the 5.0 branch.

### CODE REVIEW

**Comment by auvipy** [comment]
I am going to do this for kombu n celery tomorrow.

**Comment by thedrow** [comment]
@auvipy I for some reason don't have permission to push to py-amqp and vine.
Please restore my admin access to the organization.

**Comment by thedrow** [comment]
@auvipy Ping. I want to release Vine 5.0.0 so I can release py-amqp 5.0.0.
Please restore my permissions.

**Comment by untitaker** [comment]
y'all just released vine 5.0 which broke celery 4.3.0 as that doesn't pin vine.

**Comment by thedrow** [comment]
> y'all just released vine 5.0 which broke celery 4.3.0 as that doesn't pin vine.

Oh, I'm sorry that happened.
Maybe we can release a bugfix version that does?

**Comment by thedrow** [comment]
> y'all just released vine 5.0 which broke celery 4.3.0 as that doesn't pin vine.

Please open an issue about this on celery's repository.

**Pull request merged**
